### ISSUE TITLE
AttributeError: module 'gi' has no attribute 'require_version'

### ISSUE THREAD

**Issue by itzjustalan** [milouse/chwall#1]
paru fails installing chwall with the following message 

```
CHWALL_FAKE_INSTALL=exists python -B -m chwall.client desktop chwall-app.desktop ./locale
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/alanj/.cache/paru/clone/chwall/src/chwall-0.5.8/chwall/client.py", line 16, in <module>
    from chwall.gui.app import generate_desktop_file
  File "/home/alanj/.cache/paru/clone/chwall/src/chwall-0.5.8/chwall/gui/app.py", line 7, in <module>
    from chwall.gui.shared import ChwallGui
  File "/home/alanj/.cache/paru/clone/chwall/src/chwall-0.5.8/chwall/gui/shared.py", line 10, in <module>
    from chwall.gui.preferences import PrefDialog
  File "/home/alanj/.cache/paru/clone/chwall/src/chwall-0.5.8/chwall/gui/preferences.py", line 9, in <module>
    gi.require_version("Gtk", "3.0")
AttributeError: module 'gi' has no attribute 'require_version'
make: *** [Makefile:62: chwall-app.desktop] Error 1
rm data/icon_24x24.png data/icon_mono_16x16.png locale/fr/LC_MESSAGES/chwall.mo data/icon_mono_48x48.png data/icon_mono_32x32.png data/icon_mono_24x24.png data/icon_48x48.png locale/es/LC_MESSAGES/chwall.mo data/icon_mono_128x128.png data/icon_16x16.png data/icon_mono_64x64.png data/icon_128x128.png data/icon_32x32.png data/icon_64x64.png
==> ERROR: A failure occurred in package().
    Aborting...
error: failed to build 'chwall-0.5.8-1':
error: packages failed to build: chwall-0.5.8-1
```

**Comment by milouse** [comment]
Weird, it’s like you don’t have `python-gobject` installed on your system, but it’s a required dependency of Chwall. I don’t know Paru, but did you install all of chwall dependency before building it?

Also, can you precise what distribution you are using (archlinux, manjaro, endeavour…) ? And what exact command line did you use? Thank you very much.

**Comment by itzjustalan** [comment]
arch linux I think it broke after a system update and yes I installed chwall with paru

**Comment by milouse** [comment]
Do you still have the problem?

Can you check if all dependencies (mainly python-gobject in your case) are installed?

On archlinux, if you don’t succeed to build it, you can consider using my own custom repository: https://archlinux.umaneti.net

**Comment by itzjustalan** [comment]
turns out it was just python/pip giving random errors. most of my other python apps were affected too. and they stopped somewhere between some updates
